# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "Ignite Mumbai University 2016"
email: "praxis16org@gmail.com"
description: "Ignite is a series of speedy presentations held in cities around the world."
baseurl: ""
url: "https://ignitemu.github.io"
permalink: "/blog/:title"

# Organizer Info
organizerName: "Praxis 16"
organizerAlternateName: "Praxis 16 Technical Festival"
organizerDescription: "Ignite is all about fast and fun presentations. Speakers must build their presentations with 20 slides, each of which is shown for 15 seconds, giving each speaker 5 minutes of fame."
organizerEmail: "praxis16org@gmail.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://www.facebook.com/praxis.techfest/"

# Head
metaKeywords: "event, ignite, flashtalks, mumbai, university"
twitterAccount: "@OrthoDex"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "Ignite Mumbai <typeout> 2016"
eventDate: "September 23, 2016"
typeoutTextValues: '"", "Praxis", "Vesit"'
typeoutFallback: "University"

# About Block
aboutTitle: "About Ignite"
aboutBlock:
 - {title: "Flash Talks", image: "bolt.png", text: "Ignite presentations are speedy, lasting only 5 minutes!" }
 - {title: "Ideas", image: "light-bulb.png", text: "Hear the most outrageously unique, out of the box topics!" }
 - {title: "People", image: "people.png", text: "Meet people, learn and explore different ideas. Probably even find your calling!" }

# Statistic Block
statisticBlockImage: "statistic.gif"
statisticBlock:
 - {count: "100", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "120", specialCharacter: "+", info: "minutes", detail: "of pure ideas"}
 - {count: "17", specialCharacter: "+", info: "speakers", detail: "from college and beyond"}
 - {count: "5", specialCharacter: "", info: "minutes", detail: "of presentations"}

# Location Block
locationBlockTitle: "Location"
eventLocationName: "VESIT Seminar Hall"
eventStreetAddress: "Collector's Colony"
eventAddressLocality: "Chembur"
eventPostalCode: "400074"
eventAddressCountry: "India"
eventStartTime: "2016-09-23T14:00"
eventDoorTime: "14:00"
eventEndTime: "2016-09-23T17:00"
eventPlaceCoordinates: "19.045901,72.889055"
mapCenterCoordinates: "19.045901,72.889055"
mapMobileCenterCoordinates: "19.045901,72.889055"

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "igniteMU"

# Partners Block
organizersTitle: "Organizers"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=OrthoDex", icon: "twitter"}
 - {link: "https://www.facebook.com/events/1659425487703887/", icon: "facebook"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.facebook.com/praxis.techfest/", text: "Praxis 2016 Vesit"}
   - {link: "http://www.ignitetalks.io/", text: "Ignite Talks PBC"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:praxis16org@gmail.com", text: "praxis16org@gmail.com"}
 -

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Our aim to bring Ignite to Praxis'16 this year was to promote free thinking, and bring loads of fun into what is traditionally not popular among the youth."
